// Automatically generated on 10/19/2018, 4:18:49 PM
// Do not edit this file directly
// Version 2.0

import React from 'react';
import { Link } from 'react-router-dom';
import styles from './index.css';

export default () => (
  <div className={styles.container}>
    <div className={styles.header}>
      <h2 className={styles.title}>
        Privacy Policy
      </h2>
      <h5>
        Last Modified: October 19, 2018
      </h5>
    </div>
    <h3> Introduction </h3>
    <p className="large"> Phenominal LLC (”Company” or “We”) respect your privacy and are committed to protecting it through our compliance with this policy. </p>
    <p className="large"> This policy describes the types of information we may collect from you or that you may provide when you visit the website phenominal.fund (our “Website”) and our practices for collecting, using, maintaining, protecting, and disclosing that information. </p>
    <p className="large"> This policy applies to information we collect: </p>
    <ul>
      <li><p className="large"> On this Website. </p></li>
      <li><p className="large"> In email, text, and other electronic messages between you and this Website. </p></li>
      <li><p className="large"> When you interact with our applications on third-party websites and services, if those applications include links to this policy. </p></li>
    </ul>
    <p className="large"> It does not apply to information collected by: </p>
    <ul>
      <li><p className="large"> us offline or through any other means, including on any other website operated by Company or any third party; or </p></li>
      <li><p className="large"> any third party, including through any application or content that may link to or be accessible from or on the Website. </p></li>
    </ul>
    <p className="large"> Please read this policy carefully to understand our policies and practices regarding your information and how we will treat it. If you do not agree with our policies and practices, your choice is not to use our Website. By accessing or using this Website, you agree to this privacy policy. This policy may change from time to time (see Changes to Our Privacy Policy). Your continued use of this Website after we make changes is deemed to be acceptance of those changes, so please check the policy periodically for updates. </p>
    <hr />
    <h3> Children Under the Age of 18 </h3>
    <p className="large"> Our Website is not intended for children under 18 years of age. No one under age 18 may provide any personal information to or on the Website. We do not knowingly collect personal information from children under 18. If you are under 18, do not use or provide any information on this Website or on or through any of its features. If we learn we have collected or received personal information from a child under 18 without verification of parental consent, we will delete that information. If you believe we might have any information from or about a child under 18, please contact us at <a className="general" href="mailto:support@phenominal.fund">support@phenominal.fund</a>. </p>
    <hr />
    <h3> Information We Collect About You and How We Collect It </h3>
    <p className="large"> We collect several types of information from and about users of our Website, including information: </p>
    <ul>
      <li><p className="large"> by which you may be personally identified, such as name or e-mail address (”personal information”); </p></li>
      <li><p className="large"> that is about you but individually does not identify you, such as age or gender; and/or </p></li>
      <li><p className="large"> about your internet connection, the equipment you use to access our Website and usage details. </p></li>
    </ul>
    <p className="large"> We collect this information: </p>
    <ul>
      <li><p className="large"> Directly from you when you provide it to us. </p></li>
      <li><p className="large"> Automatically as you navigate through the site. Information collected automatically may include usage details, IP addresses, and information collected through cookies and other tracking technologies. </p></li>
      <li><p className="large"> From third parties, for example, third-party authentication. </p></li>
    </ul>
    <h4> Information You Provide to Us. </h4>
    <p className="large"> The information we collect on or through our Website may include: </p>
    <ul>
      <li><p className="large"> Information that you provide by filling in forms on our Website. This includes information provided at the time of registering to use our Website. We may also ask you for information when you report a problem with our Website. </p></li>
      <li><p className="large"> Records and copies of your correspondence (including email addresses), if you contact us. </p></li>
      <li><p className="large"> Your responses to surveys that we might ask you to complete for research purposes. </p></li>
      <li><p className="large"> Details of transactions you carry out through our Website and of the fulfillment of your orders. You may be required to provide financial information before placing an order through our Website. </p></li>
      <li><p className="large"> Your search queries on the Website. </p></li>
    </ul>
    <h4> Information We Collect Through Automatic Data Collection Technologies. </h4>
    <p className="large"> As you navigate through and interact with our Website, we may use automatic data collection technologies to collect certain information about your equipment, browsing actions, and patterns, including: </p>
    <ul>
      <li><p className="large"> Details of your visits to our Website, including location data, logs, and other communication data and the resources that you access and use on the Website. </p></li>
      <li><p className="large"> Information about your computer and internet connection, including your IP address, operating system, and browser type. </p></li>
    </ul>
    <p className="large"> The information we collect automatically is statistical data and may include personal information, or we may maintain it or associate it with personal information we collect in other ways or receive from third parties. It helps us to improve our Website and to deliver a better and more personalized service, including by enabling us to: </p>
    <ul>
      <li><p className="large"> Estimate our audience size and usage patterns. </p></li>
      <li><p className="large"> Store information about your preferences, allowing us to customize our Website according to your individual interests. </p></li>
      <li><p className="large"> Speed up your searches. </p></li>
      <li><p className="large"> Recognize you when you return to our Website. </p></li>
    </ul>
    <p className="large"> The technologies we use for this automatic data collection may include: </p>
    <ul>
      <li><p className="large"> Cookies (or browser cookies). A cookie is a small file placed on the hard drive of your computer. You may refuse to accept browser cookies by activating the appropriate setting on your browser. However, if you select this setting you may be unable to access certain parts of our Website. Unless you have adjusted your browser setting so that it will refuse cookies, our system will issue cookies when you direct your browser to our Website. </p></li>
      <li><p className="large"> Web Beacons. Pages of our the Website and our e-mails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of certain website content and verifying system and server integrity). </p></li>
      <li><p className="large"> <a target="_blank" rel="noopener noreferrer" className="general" href="https://www.google.com/analytics/terms/us.html">Google Analytics</a>. </p></li>
    </ul>
    <p className="large"> We do not collect personal information automatically, but we may tie this information to personal information about you that we collect from other sources or you provide to us. </p>
    <hr />
    <h3> How We Use Your Information </h3>
    <p className="large"> We use information that we collect about you or that you provide to us, including any personal information: </p>
    <ul>
      <li><p className="large"> To present our Website and its contents to you. </p></li>
      <li><p className="large"> To provide you with information, products, or services that you request from us. </p></li>
      <li><p className="large"> To fulfill any other purpose for which you provide it. </p></li>
      <li><p className="large"> To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection. </p></li>
      <li><p className="large"> To notify you about changes to our Website or any products or services we offer or provide though it. </p></li>
      <li><p className="large"> To allow you to participate in interactive features on our Website. </p></li>
      <li><p className="large"> In any other way we may describe when you provide the information. </p></li>
      <li><p className="large"> For any other purpose with your consent. </p></li>
    </ul>
    <hr />
    <h3> Disclosure of Your Information </h3>
    <p className="large"> We may disclose aggregated information about our users, and information that does not identify any individual, without restriction. </p>
    <p className="large"> We may disclose personal information that we collect or you provide as described in this privacy policy: </p>
    <ul>
      <li><p className="large"> To a buyer or other successor in the event of a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Phenominal LLC’s assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal information held by Phenominal LLC about our Website users is among the assets transferred. </p></li>
      <li><p className="large"> To fulfill the purpose for which you provide it. </p></li>
      <li><p className="large"> For any other purpose disclosed by us when you provide the information. </p></li>
      <li><p className="large"> With your consent. </p></li>
    </ul>
    <p className="large"> We may also disclose your personal information: </p>
    <ul>
      <li><p className="large"> To comply with any court order, law, or legal process, including to respond to any government or regulatory request. </p></li>
      <li><p className="large"> To enforce or apply our <Link className="general" to="/legal/terms">Terms of Service</Link> and other agreements, including for billing and collection purposes. </p></li>
      <li><p className="large"> If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of Phenominal LLC, our customers, or others. </p></li>
    </ul>
    <hr />
    <h3> Choices About How We Use and Disclose Your Information </h3>
    <p className="large"> Mechanisms exist to provide you with the following control over your information: </p>
    <ul>
      <li><p className="large"> Tracking Technologies. You can set your browser to refuse all or some browser cookies, or to alert you when cookies are being sent. If you disable or refuse cookies, please note that some parts of this site may then be inaccessible or not function properly. </p></li>
    </ul>
    <p className="large"> We do not control third parties’ collection or use of your information to serve interest-based advertising. However these third parties may provide you with ways to choose not to have your information collected or used in this way. </p>
    <hr />
    <h3> Accessing and Correcting Your Information </h3>
    <p className="large"> You can review and change your personal information by logging into the Website and visiting your account profile page. </p>
    <p className="large"> You may also send us an email at <a className="general" href="mailto:support@phenominal.fund">support@phenominal.fund</a> to request access to, correct or delete any personal information that you have provided to us. We cannot delete your personal information except by also deleting your user account. We may not accommodate a request to change information if we believe the change would violate any law or legal requirement or cause the information to be incorrect. </p>
    <hr />
    <h3> Data Security </h3>
    <p className="large"> We have implemented measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure. </p>
    <p className="large"> Unfortunately, the transmission of information via the internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our Website. Any transmission of personal information is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Website. </p>
    <hr />
    <h3> Changes to Our Privacy Policy </h3>
    <p className="large"> It is our policy to post any changes we make to our privacy policy on this page. If we make material changes to how we treat our users’ personal information, we will notify you by email to the email address specified in your account or through a notice on the Website home page. The date the privacy policy was last revised is identified at the top of the page. You are responsible for ensuring we have an up-to-date active and deliverable email address for you, and for periodically visiting our Website and this privacy policy to check for any changes. </p>
    <hr />
    <h3> Contact Information </h3>
    <p className="large"> To ask questions or comment about this privacy policy and our privacy practices, contact us at <a className="general" href="mailto:support@phenominal.fund">support@phenominal.fund</a>. </p>
  </div>
);
