// Automatically generated on 8/19/2018, 2:41:26 PM
// Do not edit this file directly
// Version 1.0

import React from 'react';
import { Link } from 'react-router-dom';
import styles from './index.css';

export default () => (
  <div className={styles.container}>
    <div className={styles.header}>
      <h2 className={styles.title}>
        Terms of Service
      </h2>
      <h5>
        Last Modified: June 17, 2018
      </h5>
    </div>
    <h3> Acceptance of the Terms of Service </h3>
    <p className="large"> These terms of service are entered into by and between You and Phenominal LLC (”Company”, “we”, or “us”). The following terms and conditions, together with any documents they expressly incorporate by reference (collectively, these “Terms of Service”), govern your access to and use of phenominal.fund, including any content, functionality, and services offered on or through phenominal.fund (the “Website”), whether as a guest or a registered user. </p>
    <p className="large"> Please read the Terms of Service carefully before you start to use the Website. By using the Website, you accept and agree to be bound and abide by these Terms of Service and our <Link className="general" to="/legal/privacy">Privacy Policy</Link>, incorporated herein by reference. If you do not want to agree to these Terms of Service or the Privacy Policy, you must not access or use the Website. </p>
    <p className="large"> This Website is offered and available to users who are 18 years of age or older. By using this Website, you represent and warrant that you are of legal age to form a binding contract with the Company and meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you must not access or use the Website. </p>
    <hr />
    <h3> Changes to the Terms of Service </h3>
    <p className="large"> We may revise and update these Terms of Service from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the Website thereafter. However, any changes to the dispute resolution provisions set out in Governing Law and Jurisdiction will not apply to any disputes for which the parties have actual notice on or before the date the change is posted on the Website. </p>
    <p className="large"> Your continued use of the Website following the posting of revised Terms of Service means that you accept and agree to the changes. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you. </p>
    <hr />
    <h3> Accessing the Website and Account Security </h3>
    <p className="large"> We reserve the right to withdraw or amend this Website, and any service or material we provide on the Website, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Website is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Website, or the entire Website, to users, including registered users. </p>
    <p className="large"> You are responsible for: </p>
    <ul>
      <li><p className="large"> Making all arrangements necessary for you to have access to the Website. </p></li>
      <li><p className="large"> Ensuring that all persons who access the Website through your internet connection are aware of these Terms of Service and comply with them. </p></li>
    </ul>
    <p className="large"> To access the Website or some of the resources it offers, you may be asked to provide certain registration details or other information. It is a condition of your use of the Website that all the information you provide on the Website is correct, current, and complete. You agree that all information you provide to register with this Website or otherwise, including but not limited to through the use of any interactive features on the Website, is governed by our <Link className="general" to="/legal/privacy">Privacy Policy</Link>, and you consent to all actions we take with respect to your information consistent with our Privacy Policy. </p>
    <p className="large"> If you choose, or are provided with, a user name, password, or any other piece of information as part of our security procedures, you must treat such information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person with access to this Website or portions of it using your user name, password, or other security information. You agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security. You also agree to ensure that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. </p>
    <p className="large"> We have the right to disable any user name, password, or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms of Service. </p>
    <hr />
    <h3> Intellectual Property Rights </h3>
    <p className="large"> The Website and its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) are owned by the Company, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. </p>
    <p className="large"> These Terms of Service permit you to use the Website for your personal, non-commercial use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Website, except as follows: </p>
    <ul>
      <li><p className="large"> Your computer may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials. </p></li>
      <li><p className="large"> You may store files that are automatically cached by your Web browser for display enhancement purposes. </p></li>
      <li><p className="large"> You may print or download one copy of a reasonable number of pages of the Website for your own personal, non-commercial use and not for further reproduction, publication, or distribution. </p></li>
      <li><p className="large"> If we provide desktop, mobile, or other applications for download, you may download a single copy to your computer or mobile device solely for your own personal, non-commercial use, provided you agree to be bound by our end user license agreement for such applications. </p></li>
    </ul>
    <p className="large"> You must not: </p>
    <ul>
      <li><p className="large"> Modify copies of any materials from this site. </p></li>
      <li><p className="large"> Use any illustrations, photographs, video or audio sequences, or any graphics separately from the accompanying text. </p></li>
      <li><p className="large"> Delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from this site. </p></li>
    </ul>
    <p className="large"> You must not access or use for any commercial purposes any part of the Website or any services or materials available through the Website. </p>
    <p className="large"> If you wish to make any use of material on the Website other than that set out in this section, please address your request to: <a className="general" href="mailto:support@phenominal.fund">support@phenominal.fund</a>. </p>
    <p className="large"> If you print, copy, modify, download, or otherwise use or provide any other person with access to any part of the Website in breach of the Terms of Service, your right to use the Website will stop immediately and you must, at our option, return or destroy any copies of the materials you have made. No right, title, or interest in or to the Website or any content on the Website is transferred to you, and all rights not expressly granted are reserved by the Company. Any use of the Website not expressly permitted by these Terms of Service is a breach of these Terms of Service and may violate copyright, trademark, and other laws. </p>
    <hr />
    <h3> Trademarks </h3>
    <p className="large"> The Company name, the Company logo, and all related names, logos, product and service names, designs, and slogans are trademarks of the Company or its affiliates or licensors. You must not use such marks without the prior written permission of the Company. All other names, logos, product and service names, designs, and slogans on this Website are the trademarks of their respective owners. </p>
    <hr />
    <h3> Prohibited Uses </h3>
    <p className="large"> You may use the Website only for lawful purposes and in accordance with these Terms of Service. You agree not to use the Website: </p>
    <ul>
      <li><p className="large"> In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries). </p></li>
      <li><p className="large"> For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise. </p></li>
      <li><p className="large"> To transmit, or procure the sending of, any advertising or promotional material without our prior written consent, including any “junk mail”, “chain letter”, “spam”, or any other similar solicitation. </p></li>
      <li><p className="large"> To impersonate or attempt to impersonate the Company, a Company employee, another user, or any other person or entity (including, without limitation, by using email addresses associated with any of the foregoing). </p></li>
      <li><p className="large"> To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of the Website, or which, as determined by us, may harm the Company or users of the Website or expose them to liability. </p></li>
    </ul>
    <p className="large"> Additionally, you agree not to: </p>
    <ul>
      <li><p className="large"> Use the Website in any manner that could disable, overburden, damage, or impair the site or interfere with any other party’s use of the Website, including their ability to engage in real time activities through the Website. </p></li>
      <li><p className="large"> Use any manual process to monitor or copy any of the material on the Website or for any other unauthorized purpose without our prior written consent. </p></li>
      <li><p className="large"> Use any device, software, or routine that interferes with the proper working of the Website. </p></li>
      <li><p className="large"> Introduce any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful. </p></li>
      <li><p className="large"> Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Website, the server on which the Website is stored, or any server, computer, or database connected to the Website. </p></li>
      <li><p className="large"> Attack the Website via a denial-of-service attack or a distributed denial-of-service attack. </p></li>
      <li><p className="large"> Otherwise attempt to interfere with the proper working of the Website. </p></li>
    </ul>
    <hr />
    <h3> Reliance on Information Posted </h3>
    <p className="large"> The information presented on or through the Website is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Website, or by anyone who may be informed of any of its contents. </p>
    <hr />
    <h3> Changes to the Website </h3>
    <p className="large"> We may update the content on this Website from time to time, but its content is not necessarily complete or up-to-date. Any of the material on the Website may be out of date at any given time, and we are under no obligation to update such material. </p>
    <hr />
    <h3> Information About You and Your Visits to the Website </h3>
    <p className="large"> All information we collect on this Website is subject to our <Link className="general" to="/legal/privacy">Privacy Policy</Link>. By using the Website, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy. </p>
    <hr />
    <h3> Linking to the Website and Social Media Features </h3>
    <p className="large"> You may link to our homepage, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval, or endorsement on our part without our express consent. </p>
    <p className="large"> This Website may provide certain social media features that enable you to: </p>
    <ul>
      <li><p className="large"> Link from your own or certain third-party websites to certain content on this Website. </p></li>
      <li><p className="large"> Send emails or other communications with certain content, or links to certain content, on this Website. </p></li>
      <li><p className="large"> Cause limited portions of content on this Website to be displayed or appear to be displayed on your own or certain third-party websites. </p></li>
    </ul>
    <p className="large"> You may use these features solely as they are provided by us solely with respect to the content they are displayed with. Subject to the foregoing, you must not: </p>
    <ul>
      <li><p className="large"> Establish a link from any website that is not owned by you. </p></li>
      <li><p className="large"> Cause the Website or portions of it to be displayed on, or appear to be displayed by, any other site, for example, framing, deep linking, or in-line linking. </p></li>
      <li><p className="large"> Link to any part of the Website other than the homepage. </p></li>
      <li><p className="large"> Otherwise take any action with respect to the materials on this Website that is inconsistent with any other provision of these Terms of Service. </p></li>
    </ul>
    <p className="large"> You agree to cooperate with us in causing any unauthorized framing or linking immediately to stop. We reserve the right to withdraw linking permission without notice. </p>
    <p className="large"> We may disable all or any social media features and any links at any time without notice in our discretion. </p>
    <hr />
    <h3> Links from the Website </h3>
    <p className="large"> If the Website contains links to other sites and resources provided by third parties, these links are provided for your convenience only. We have no control over the contents of those sites or resources, and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third-party websites linked to this Website, you do so entirely at your own risk and subject to the terms and conditions of use for such websites. </p>
    <hr />
    <h3> Geographic Restrictions </h3>
    <p className="large"> The owner of the Website is based in the state of New York in the United States. We provide this Website for use only by persons located in the United States. We make no claims that the Website or any of its content is accessible or appropriate outside of the United States. Access to the Website may not be legal by certain persons or in certain countries. If you access the Website from outside the United States, you do so on your own initiative and are responsible for compliance with local laws. </p>
    <hr />
    <h3> Disclaimer of Warranties </h3>
    <p className="large"> You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or the Website will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON IT, OR ON ANY WEBSITE LINKED TO IT. </p>
    <p className="large"> YOUR USE OF THE WEBSITE, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE IS AT YOUR OWN RISK. THE WEBSITE, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER THE COMPANY NOR ANY PERSON ASSOCIATED WITH THE COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE WEBSITE. WITHOUT LIMITING THE FOREGOING, NEITHER THE COMPANY NOR ANYONE ASSOCIATED WITH THE COMPANY REPRESENTS OR WARRANTS THAT THE WEBSITE, ITS CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT OUR SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS. </p>
    <p className="large"> TO THE FULLEST EXTENT PROVIDED BY LAW, THE COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE. </p>
    <p className="large"> THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. </p>
    <hr />
    <h3> Limitation on Liability </h3>
    <p className="large"> TO THE FULLEST EXTENT PROVIDED BY LAW, IN NO EVENT WILL THE COMPANY, ITS AFFILIATES, OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE WEBSITE, ANY WEBSITES LINKED TO IT, ANY CONTENT ON THE WEBSITE OR SUCH OTHER WEBSITES, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE. </p>
    <p className="large"> THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. </p>
    <hr />
    <h3> Indemnification </h3>
    <p className="large"> You agree to defend, indemnify, and hold harmless the Company, its affiliates, licensors, and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys’ fees) arising out of or relating to your violation of these Terms of Service or your use of the Website, including, but not limited to, your User Contributions, any use of the Website’s content, services, and products other than as expressly authorized in these Terms of Service or your use of any information obtained from the Website. </p>
    <hr />
    <h3> Governing Law and Jurisdiction </h3>
    <p className="large"> All matters relating to the Website and these Terms of Service and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the internal laws of the State of New York without giving effect to any choice or conflict of law provision or rule (whether of the State of New York or any other jurisdiction). </p>
    <p className="large"> Any legal suit, action, or proceeding arising out of, or related to, these Terms of Service or the Website shall be instituted exclusively in the federal courts of the United States or the courts of the State of New York although we retain the right to bring any suit, action, or proceeding against you for breach of these Terms of Service in your country of residence or any other relevant country. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts. </p>
    <hr />
    <h3> Limitation on Time to File Claims </h3>
    <p className="large"> ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE OR THE WEBSITE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED. </p>
    <hr />
    <h3> Waiver and Severability </h3>
    <p className="large"> No waiver by the Company of any term or condition set out in these Terms of Service shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms of Service shall not constitute a waiver of such right or provision. </p>
    <p className="large"> If any provision of these Terms of Service is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Service will continue in full force and effect. </p>
    <hr />
    <h3> Entire Agreement </h3>
    <p className="large"> The Terms of Service and our Privacy Policy constitute the sole and entire agreement between you and Phenominal LLC regarding the Website and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding the Website. </p>
    <hr />
    <h3> Your Comments and Concerns </h3>
    <p className="large"> This website is operated by Phenominal LLC, 51 Woodworth Street, Victor, New York 14564. </p>
    <p className="large"> All other feedback, comments, requests for technical support, and other communications relating to the Website should be directed to: <a className="general" href="mailto:support@phenominal.fund">support@phenominal.fund</a>. </p>
  </div>
);
